pipeline{
    agent any
    stages{
        stage('passo1'){
            steps{
                echo'steps 1'
            }
        }
        stage('passo2'){
            steps{
                echo'steps 1'
            }
        }
    }
}
